# -*- coding: utf-8 -*-
{
    "name": 'Laundry Configuration',
    "version": '18.0.1.0.0',
    "category": 'Services/Laundry',
    "author": "LeadSolutions Cia. Ltda.",
    "website": "https://lidsus.com/",
    "support": "info@leadsolutions.ec",
    "license": "AGPL-3",
    "price": 0,
    "currency": "USD",
    'summary': 'Catalog configuration for the laundry application',
    'depends': ['base',
                'stock',
                'product',
                'account',
                'sale',
                'sale_stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/laundry_method_type_data.xml',
        'data/laundry_method_data.xml',
        'data/laundry_claim_catalogue_data.xml',
        'data/product_category_data.xml',
        'data/product_data.xml',
        'views/laundry_config_view.xml',
    ],
    'images': [
        'static/description/laundry_ec.png',
        'static/description/icon.png',
        'static/description/cover.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
