# -*- coding: utf-8 -*-
{
    'name': 'Laundry Management - LeadSolutions',
    "version": '18.0.1.0.0',
    "category": 'Services/Laundry',
    "author": "LeadSolutions Cia. Ltda.",
    "website": "https://lidsus.com/",
    "support": "info@leadsolutions.ec",
    "license": "AGPL-3",
    "price": 0,
    "currency": "USD",
    'summary': 'Gestión de órdenes de servicio de lavandería',
    'depends': [
        'laundry_configuration',
    ],
    'data': [
        'security/laundry_security.xml',
        'security/ir.model.access.csv',
        'data/laundry_sequence.xml',
        'data/laundry_delivery_guide_sequence.xml',
        'data/laundry_dispatch_guide_sequence.xml',
        'views/laundry_management_view.xml',
        'views/laundry_claim_view.xml',
        'views/laundry_guia_entrega_view.xml',
        'views/laundry_recibe_guia_entrega_view.xml',
        'views/laundry_guia_despacho_view.xml',
        'views/laundry_recibe_guia_despacho_view.xml',
        'views/report_laundry_order.xml',
        'views/report_laundry_order_chofer.xml',
        'views/report_laundry_delivery_guide.xml',
        'views/report_laundry_dispatch_guide.xml',
        'views/report_laundry_claim.xml',
        'wizard/laundry_make_invoice_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
